In [3]:
!pip install scikit-learn

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 9.1/9.1 MB 122.6 MB/s eta 0:00:00
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 35.3/35.3 MB 148.5 MB/s eta 0:00:0000:01
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 16.7/16.7 MB 140.7 MB/s eta 0:00:00
  Attempting uninstall: numpy
    Found existing installation: numpy 1.26.4
    Uninstalling numpy-1.26.4:
      Successfully uninstalled numpy-1.26.4


In [5]:
!pip install pandas numpy matplotlib seaborn

In [1]:
import pandas as pd
import numpy as np

import matplotlib.pyplot as plt
import seaborn as sns

from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.neighbors import KNeighborsClassifier
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

from sklearn.metrics import (
    accuracy_score,
    roc_auc_score,
    precision_score,
    recall_score,
    f1_score,
    matthews_corrcoef,
    confusion_matrix,
    classification_report
)

import warnings
warnings.filterwarnings("ignore")

print("Libraries imported successfully!")

Libraries imported successfully!


In [3]:
url = "https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/wdbc.data"

columns = [
    "ID", "Diagnosis",
    "Radius_Mean", "Texture_Mean", "Perimeter_Mean", "Area_Mean",
    "Smoothness_Mean", "Compactness_Mean", "Concavity_Mean",
    "Concave_Points_Mean", "Symmetry_Mean", "Fractal_Dimension_Mean",

    "Radius_SE", "Texture_SE", "Perimeter_SE", "Area_SE",
    "Smoothness_SE", "Compactness_SE", "Concavity_SE",
    "Concave_Points_SE", "Symmetry_SE", "Fractal_Dimension_SE",

    "Radius_Worst", "Texture_Worst", "Perimeter_Worst", "Area_Worst",
    "Smoothness_Worst", "Compactness_Worst", "Concavity_Worst",
    "Concave_Points_Worst", "Symmetry_Worst", "Fractal_Dimension_Worst"
]

df = pd.read_csv(url, header=None, names=columns)

print("Dataset loaded successfully!")
print("Shape:", df.shape)

df.head()

Dataset loaded successfully!
Shape: (569, 32)


,ID,Diagnosis,Radius_Mean,Texture_Mean,Perimeter_Mean,Area_Mean,Smoothness_Mean,Compactness_Mean,Concavity_Mean,Concave_Points_Mean,...,Radius_Worst,Texture_Worst,Perimeter_Worst,Area_Worst,Smoothness_Worst,Compactness_Worst,Concavity_Worst,Concave_Points_Worst,Symmetry_Worst,Fractal_Dimension_Worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [5]:
print("Dataset Shape:", df.shape)
print("\nData Types:")
print(df.dtypes)

print("\nMissing Values:")
print(df.isnull().sum().sum())

print("\nTarget Distribution:")
print(df["Diagnosis"].value_counts())

print("\nFirst 5 Rows:")
display(df.head())

Dataset Shape: (569, 32)

Data Types:
ID                           int64
Diagnosis                   object
Radius_Mean                float64
Texture_Mean               float64
Perimeter_Mean             float64
Area_Mean                  float64
Smoothness_Mean            float64
Compactness_Mean           float64
Concavity_Mean             float64
Concave_Points_Mean        float64
Symmetry_Mean              float64
Fractal_Dimension_Mean     float64
Radius_SE                  float64
Texture_SE                 float64
Perimeter_SE               float64
Area_SE                    float64
Smoothness_SE              float64
Compactness_SE             float64
Concavity_SE               float64
Concave_Points_SE          float64
Symmetry_SE                float64
Fractal_Dimension_SE       float64
Radius_Worst               float64
Texture_Worst              float64
Perimeter_Worst            float64
Area_Worst                 float64
Smoothness_Worst           float64
Compactness_Worst

,ID,Diagnosis,Radius_Mean,Texture_Mean,Perimeter_Mean,Area_Mean,Smoothness_Mean,Compactness_Mean,Concavity_Mean,Concave_Points_Mean,...,Radius_Worst,Texture_Worst,Perimeter_Worst,Area_Worst,Smoothness_Worst,Compactness_Worst,Concavity_Worst,Concave_Points_Worst,Symmetry_Worst,Fractal_Dimension_Worst
0,842302,M,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.3001,0.14710,...,25.38,17.33,184.60,2019.0,0.1622,0.6656,0.7119,0.2654,0.4601,0.11890
1,842517,M,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.0869,0.07017,...,24.99,23.41,158.80,1956.0,0.1238,0.1866,0.2416,0.1860,0.2750,0.08902
2,84300903,M,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.1974,0.12790,...,23.57,25.53,152.50,1709.0,0.1444,0.4245,0.4504,0.2430,0.3613,0.08758
3,84348301,M,11.42,20.38,77.58,386.1,0.14250,0.28390,0.2414,0.10520,...,14.91,26.50,98.87,567.7,0.2098,0.8663,0.6869,0.2575,0.6638,0.17300
4,84358402,M,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.1980,0.10430,...,22.54,16.67,152.20,1575.0,0.1374,0.2050,0.4000,0.1625,0.2364,0.07678


In [7]:
# Remove the ID column because it has no predictive value
X = df.drop(columns=["ID", "Diagnosis"])

# Convert target:
# M (Malignant) = 1
# B (Benign) = 0
y = df["Diagnosis"].map({"M": 1, "B": 0})

# Split the dataset into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("Training samples:", X_train.shape[0])
print("Testing samples:", X_test.shape[0])
print("Number of features:", X_train.shape[1])

Training samples: 455
Testing samples: 114
Number of features: 30


In [9]:
def evaluate_model(model, X_train, X_test, y_train, y_test):
    # Train the model
    model.fit(X_train, y_train)

    # Predictions
    y_pred = model.predict(X_test)

    # Probability scores for AUC
    y_prob = model.predict_proba(X_test)[:, 1]

    # Calculate metrics
    accuracy = accuracy_score(y_test, y_pred)
    auc = roc_auc_score(y_test, y_prob)
    precision = precision_score(y_test, y_pred)
    recall = recall_score(y_test, y_pred)
    f1 = f1_score(y_test, y_pred)
    mcc = matthews_corrcoef(y_test, y_pred)

    return {
        "Accuracy": accuracy,
        "AUC": auc,
        "Precision": precision,
        "Recall": recall,
        "F1 Score": f1,
        "MCC": mcc
    }

In [11]:
# Scale features for Logistic Regression
scaler_lr = StandardScaler()

X_train_scaled = scaler_lr.fit_transform(X_train)
X_test_scaled = scaler_lr.transform(X_test)

# Create Logistic Regression model
logistic_model = LogisticRegression(random_state=42, max_iter=1000)

# Evaluate
logistic_results = evaluate_model(
    logistic_model,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

print("Logistic Regression Results:")
for metric, value in logistic_results.items():
    print(f"{metric}: {value:.4f}")

Logistic Regression Results:
Accuracy: 0.9649
AUC: 0.9960
Precision: 0.9750
Recall: 0.9286
F1 Score: 0.9512
MCC: 0.9245


In [13]:
# Scale features for Logistic Regression
scaler_lr = StandardScaler()

X_train_scaled = scaler_lr.fit_transform(X_train)
X_test_scaled = scaler_lr.transform(X_test)

# Create Logistic Regression model
logistic_model = LogisticRegression(random_state=42, max_iter=1000)

# Evaluate
logistic_results = evaluate_model(
    logistic_model,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)

print("Logistic Regression Results:")
for metric, value in logistic_results.items():
    print(f"{metric}: {value:.4f}")

Logistic Regression Results:
Accuracy: 0.9649
AUC: 0.9960
Precision: 0.9750
Recall: 0.9286
F1 Score: 0.9512
MCC: 0.9245


In [15]:
# Dictionary to store results for all models
results = {}

# Store Logistic Regression results
results["Logistic Regression"] = logistic_results


# 1. Decision Tree
decision_tree_model = DecisionTreeClassifier(
    random_state=42
)

results["Decision Tree"] = evaluate_model(
    decision_tree_model,
    X_train,
    X_test,
    y_train,
    y_test
)


# 2. K-Nearest Neighbors
knn_model = KNeighborsClassifier(
    n_neighbors=5
)

results["KNN"] = evaluate_model(
    knn_model,
    X_train_scaled,
    X_test_scaled,
    y_train,
    y_test
)


# 3. Gaussian Naive Bayes
naive_bayes_model = GaussianNB()

results["Naive Bayes"] = evaluate_model(
    naive_bayes_model,
    X_train,
    X_test,
    y_train,
    y_test
)


# 4. Random Forest
random_forest_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

results["Random Forest"] = evaluate_model(
    random_forest_model,
    X_train,
    X_test,
    y_train,
    y_test
)


print("All five models trained and evaluated successfully!")

All five models trained and evaluated successfully!


In [17]:
results_df = pd.DataFrame(results).T

results_df = results_df.round(4)

display(results_df)

,Accuracy,AUC,Precision,Recall,F1 Score,MCC
Logistic Regression,0.9649,0.9960,0.9750,0.9286,0.9512,0.9245
Decision Tree,0.9298,0.9246,0.9048,0.9048,0.9048,0.8492
KNN,0.9561,0.9823,0.9744,0.9048,0.9383,0.9058
Naive Bayes,0.9386,0.9934,1.0000,0.8333,0.9091,0.8715
Random Forest,0.9737,0.9929,1.0000,0.9286,0.9630,0.9442


In [19]:
models = {
    "Logistic Regression": logistic_model,
    "Decision Tree": decision_tree_model,
    "KNN": knn_model,
    "Naive Bayes": naive_bayes_model,
    "Random Forest": random_forest_model
}

# Use the appropriate test data for each model
test_data_for_model = {
    "Logistic Regression": X_test_scaled,
    "Decision Tree": X_test,
    "KNN": X_test_scaled,
    "Naive Bayes": X_test,
    "Random Forest": X_test
}

for name, model in models.items():
    X_eval = test_data_for_model[name]
    y_pred = model.predict(X_eval)

    print("=" * 60)
    print(name)
    print("=" * 60)

    print("\nConfusion Matrix:")
    print(confusion_matrix(y_test, y_pred))

    print("\nClassification Report:")
    print(classification_report(
        y_test,
        y_pred,
        target_names=["Benign", "Malignant"]
    ))

Logistic Regression

Confusion Matrix:
[[71  1]
 [ 3 39]]

Classification Report:
              precision    recall  f1-score   support

      Benign       0.96      0.99      0.97        72
   Malignant       0.97      0.93      0.95        42

    accuracy                           0.96       114
   macro avg       0.97      0.96      0.96       114
weighted avg       0.97      0.96      0.96       114

Decision Tree

Confusion Matrix:
[[68  4]
 [ 4 38]]

Classification Report:
              precision    recall  f1-score   support

      Benign       0.94      0.94      0.94        72
   Malignant       0.90      0.90      0.90        42

    accuracy                           0.93       114
   macro avg       0.92      0.92      0.92       114
weighted avg       0.93      0.93      0.93       114

KNN

Confusion Matrix:
[[71  1]
 [ 4 38]]

Classification Report:
              precision    recall  f1-score   support

      Benign       0.95      0.99      0.97        72
   Malignant 

In [21]:
# Create test dataset with features + target
test_data = X_test.copy()

# Convert target back to readable labels
test_data["Diagnosis"] = y_test.map({
    0: "B",
    1: "M"
})

# Save test data
test_data.to_csv("test_data.csv", index=False)

print("test_data.csv created successfully!")
print("Test data shape:", test_data.shape)

display(test_data.head())

test_data.csv created successfully!
Test data shape: (114, 31)


,Radius_Mean,Texture_Mean,Perimeter_Mean,Area_Mean,Smoothness_Mean,Compactness_Mean,Concavity_Mean,Concave_Points_Mean,Symmetry_Mean,Fractal_Dimension_Mean,...,Texture_Worst,Perimeter_Worst,Area_Worst,Smoothness_Worst,Compactness_Worst,Concavity_Worst,Concave_Points_Worst,Symmetry_Worst,Fractal_Dimension_Worst,Diagnosis
120,11.41,10.82,73.34,403.3,0.09373,0.06685,0.03512,0.02623,0.1667,0.06113,...,15.97,83.74,510.5,0.1548,0.2390,0.21020,0.08958,0.3016,0.08523,B
250,20.94,23.56,138.90,1364.0,0.10070,0.16060,0.27120,0.13100,0.2205,0.05898,...,27.00,165.30,2010.0,0.1211,0.3172,0.69910,0.21050,0.3126,0.07849,M
375,16.17,16.07,106.30,788.5,0.09880,0.14380,0.06651,0.05397,0.1990,0.06572,...,19.14,113.10,861.5,0.1235,0.2550,0.21140,0.12510,0.3153,0.08960,B
99,14.42,19.77,94.48,642.5,0.09752,0.11410,0.09388,0.05839,0.1879,0.06390,...,30.86,109.50,826.4,0.1431,0.3026,0.31940,0.15650,0.2718,0.09353,M
455,13.38,30.72,86.34,557.2,0.09245,0.07426,0.02819,0.03264,0.1375,0.06016,...,41.61,96.69,705.6,0.1172,0.1421,0.07003,0.07763,0.2196,0.07675,B


In [23]:
import joblib
import os

# Create model directory
os.makedirs("model", exist_ok=True)

# Save all five models
joblib.dump(logistic_model, "model/logistic_regression.pkl")
joblib.dump(decision_tree_model, "model/decision_tree.pkl")
joblib.dump(knn_model, "model/knn.pkl")
joblib.dump(naive_bayes_model, "model/naive_bayes.pkl")
joblib.dump(random_forest_model, "model/random_forest.pkl")

# Save scalers required by Logistic Regression and KNN
joblib.dump(scaler_lr, "model/scaler.pkl")

print("All models saved successfully!")

All models saved successfully!


In [13]:
import os

project_folder = "/home/cloud/ML_Classification_Project"

for root, dirs, files in os.walk(project_folder):
    level = root.replace(project_folder, "").count(os.sep)
    indent = "    " * level

    print(f"{indent}{os.path.basename(root)}/")

    for file in files:
        print(f"{indent}    {file}")

ML_Classification_Project/
    test_data.csv
    ML_Experimentation.ipynb
    app.py
    requirements.txt
    README.md
    model/
        logistic_regression.pkl
        decision_tree.pkl
        knn.pkl
        naive_bayes.pkl
        random_forest.pkl
        scaler.pkl
